language: python
env:
  global:
    - CI=true
sudo: false

matrix:
  include:
    - os: osx
      language: generic
      env: 'JOB=osx-vm-python3'
    - os: linux
      python: '3.5'
      env: 'JOB=linux-container-python3.5'
    - os: linux
      python: '3.4'
      env: 'JOB=linux-container-python3.4'
    - sudo: required
      dist: trusty
      python: '3.5'
      env: 'JOB=ubuntu14-vm-python3.5'
    - sudo: required
      dist: precise
      python: '3.5'
      env: 'JOB=ubuntu12-vm-python3.5'

install: ./travis/install.sh

script:
    - make dir_test
    - py.test

branches:
  only:
    - "master"
    - "ci-olehermanse"
    - "ci-berstad"

notifications:
    email: false
